services:
  mysql:
    image: mysql:8.0.42
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root   # root 계정 비밀번호
      MYSQL_DATABASE: health_mng    # 초기 생성할 DB 이름
    ports:
      - "3306:3306"
    networks:
      - backend
    tmpfs:
      - /var/lib/mysql
    healthcheck:                # MySQL 정상 작동 여부 확인용 설정
      test: ["CMD", "mysqladmin", "ping", "-h", "mysql", "-uroot", "-proot"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 30s

  health:
    build:
      context: ./
    container_name: health
    depends_on:
      mysql:
        condition: service_healthy  # MySQL이 정상 동작할 때만 시작
    ports:
      - "8080:8080"
    networks:
      - backend

networks:
  backend:  # 서비스 간 통신을 위한 가상 네트워크 정의